version: '3.8'

services:
  frontend:
    image: wotklaus86682/frontbackdb:frontend    # Imagen frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: wotklaus86682/frontbackdb:backend     # Imagen backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGUSER=postgres
      - PGPASSWORD=123
      - PGHOST=postgres
      - PGDATABASE=pokemon
      - PGPORT=5432
      - JWT_SECRET=mi_super_secreto
      - JWT_EXPIRES_IN=2m
      - JWT_REFRESH_SECRET=mi_super_secreto_refresh
      - JWT_REFRESH_EXPIRES_IN=7d

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pokemon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  pgdata: